package hu.neuron.java.core;

import hu.neuron.java.core.dao.RoleDAO;
import hu.neuron.java.core.dao.impl.UserDAOImpl;
import hu.neuron.java.core.dto.RoleDTO;

import java.sql.DatabaseMetaData;
import java.sql.ResultSet;

import javax.sql.DataSource;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@Component
@Transactional(propagation = Propagation.REQUIRED)
public class CreateShema {
	private static final Logger logger = Logger.getLogger(UserDAOImpl.class);

	private JdbcTemplate jdbcTemplate;

	@Autowired
	public void setDataSource(DataSource dataSource) {
		this.jdbcTemplate = new JdbcTemplate(dataSource);
	}

	@Autowired
	public RoleDAO roleDAO;

	public void create() {
		try {
			String db = jdbcTemplate.getDataSource().getConnection()
					.getMetaData().getDatabaseProductName();

			DatabaseMetaData meta = jdbcTemplate.getDataSource()
					.getConnection().getMetaData();
			ResultSet res = meta.getTables(null, null, "user",
					new String[] { "TABLE" });
			if (!res.next()) {
				if (db.equals("MySQL")) {

					this.jdbcTemplate
							.execute("create table user (ID int  NOT NULL AUTO_INCREMENT , name varchar(100),password varchar(100),PRIMARY KEY ( id ))");

					this.jdbcTemplate
							.execute("create table role (ID int  NOT NULL AUTO_INCREMENT , name varchar(100),PRIMARY KEY ( id ))");

					this.jdbcTemplate
							.execute("create table user_role_sw (ID int NOT NULL AUTO_INCREMENT, user_id int,role_id int,PRIMARY KEY ( id ))");
				} else {
					this.jdbcTemplate
							.execute("create table user (ID int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) , name varchar(100),password varchar(100))");

					this.jdbcTemplate
							.execute("create table role (ID int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) , name varchar(100))");

					this.jdbcTemplate
							.execute("create table user_role_sw (ID int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) , user_id int,role_id int)");

				}
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		}
	}

	public void insertRoles() {
		RoleDTO dto = null;
		try {
			if (roleDAO.findRoleByName("ROLE_USER") == null) {
				dto = new RoleDTO(null, "ROLE_USER");
				roleDAO.save(dto);
			}
			if (roleDAO.findRoleByName("ROLE_ADMIN") == null) {
				dto = new RoleDTO(null, "ROLE_ADMIN");
				roleDAO.save(dto);
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		}
	}

}
